templates_test/upsert.go.tpl: add missing newline
This fixes a template error

❯ sqlboiler crdb
Error: unable to generate test output: failed to format template

  60            t.Error(err)
  61    }
  62    if count != 1 {
  63            t.Error("want one record, got:", count)
  64    }
>>>> }var (
  66     // Relationships sometimes use the reflection helper queries.Equal/queries.Assign
  67     // so force a package dependency in case they don't.
  68     _ = queries.Equal
  69 )
  70 func testAttributes(t *testing.T) {

: 65:2: expected ';', found 'var'